const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
const base=process.env.TEST_BASE_URL||'http://127.0.0.1:4173';
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'}),page=await browser.newPage({viewport:{width:1500,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{window.registeredTools=[];Object.defineProperty(document,'modelContext',{value:{registerTool:t=>window.registeredTools.push(t)}});});
 await page.goto(base);await page.getByRole('heading',{name:'What are we working on?'}).waitFor();
 assert.equal(await page.getByRole('button',{name:/demo|compare drafts/i}).count(),0);
 fs.mkdirSync('test-results',{recursive:true});await page.screenshot({path:'test-results/chat-desktop.png'});
 const send=async text=>{await page.getByRole('textbox',{name:'Message Product assistant'}).fill(text);await page.getByRole('button',{name:'Send message',exact:true}).click();};
 const generate=()=>page.getByRole('button',{name:'Draft with approved context',exact:true}).last();
 await send('/prd Certificate Alert Filtering');
 await page.getByRole('button',{name:'Approve non-conflicting items'}).click();assert.equal(await generate().isDisabled(),true);
 await page.getByRole('button',{name:'Use September scope'}).click();
 await page.locator('[data-memory="m1"]').getByRole('button',{name:'Edit',exact:true}).click();await page.locator('#memory-edit').fill('Security teams with 50+ domains');await page.getByRole('button',{name:'Save for review'}).click();
 await page.locator('[data-memory="m1"]').getByRole('button',{name:'Approve',exact:true}).click();
 await page.locator('[data-memory="m4"]').getByRole('button',{name:'Reject',exact:true}).click();
 await page.locator('[data-memory="m5"]').getByRole('checkbox').uncheck();
 await generate().click();await page.locator('.draft-document').waitFor();
 const firstDraft=await page.locator('.draft-content').textContent();assert.ok(firstDraft.includes('50+ domains'));assert.ok(!firstDraft.includes('Reduction in unnecessary'));assert.ok(!firstDraft.includes('Preserve existing alert'));
 const originalReceiptPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download receipt',exact:true}).click();const originalReceipt=JSON.parse(fs.readFileSync(await(await originalReceiptPromise).path(),'utf8'));assert.equal(originalReceipt.contextSupplied.length,4);assert.equal(originalReceipt.excluded.length,2);
 await page.screenshot({path:'test-results/chat-draft.png'});
 const addNote=async(text,title='New product decision')=>{await page.getByRole('button',{name:'Add context',exact:true}).first().click();await page.getByRole('textbox',{name:'Source name'}).fill(title);await page.getByRole('textbox',{name:'Project note',exact:true}).fill(text);await page.getByRole('button',{name:'Review suggestions'}).click();};
 await addNote('Beta launch: October 22, 2026');assert.equal(await generate().isDisabled(),true);await page.getByRole('button',{name:'Use update',exact:true}).click();await generate().click();await page.locator('.draft-document').nth(1).waitFor();assert.ok((await page.locator('.draft-content').last().textContent()).includes('October 22, 2026'));
 assert.ok(!firstDraft.includes('October 22, 2026'));assert.ok(originalReceipt.contextSupplied.some(x=>x.text==='October 15, 2026'));
 await page.getByRole('button',{name:'New chat',exact:true}).first().click();await send('/prd Certificate Alert Filtering');await page.locator('.draft-document').waitFor();assert.ok((await page.locator('.draft-content').textContent()).includes('October 22, 2026'));assert.equal(await page.getByRole('button',{name:'Draft with approved context',exact:true}).count(),0);
 await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByRole('textbox',{name:'Project name'}).fill('Mobile Checkout');await page.getByRole('button',{name:'Create project',exact:true}).click();
 await send('/prd Mobile Checkout');await page.getByRole('button',{name:'Add project notes',exact:true}).click();await page.getByRole('textbox',{name:'Source name'}).fill('Checkout decisions');
 await page.locator('#text-file').setInputFiles({name:'decisions.md',mimeType:'text/markdown',buffer:Buffer.from('Scope: Mobile only\nMetric: Weekly retention\nConstraint: <img src=x onerror=alert(1)> remains literal text')});
 await page.getByRole('button',{name:'Review suggestions'}).click();assert.equal(await page.locator('img').count(),0);await page.getByRole('button',{name:'Approve non-conflicting items'}).click();await generate().click();await page.locator('.draft-document').waitFor();assert.ok((await page.locator('.draft-content').textContent()).includes('Mobile only'));assert.ok(!(await page.locator('.draft-content').textContent()).includes('Certificate'));
 await send('Make it shorter');assert.equal(await page.locator('.draft-document').count(),1);assert.ok((await page.locator('.thread').textContent()).includes('live AI needs to be connected'));
 const tools=await page.evaluate(async()=>{const read=await window.registeredTools.find(t=>t.name==='read_context_review').execute({});const stage=window.registeredTools.find(t=>t.name==='stage_context_review');let rejected=false;try{await stage.execute({extra:1});}catch{rejected=true;}await stage.execute({});return{count:read.items.length,rejected};});assert.equal(tools.count,3);assert.equal(tools.rejected,true);
 for(const width of [390,768,1500]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`overflow at ${width}`);}
 await page.setViewportSize({width:390,height:844});await page.reload();await page.getByRole('heading',{name:'What are we working on?'}).waitFor();await page.screenshot({path:'test-results/chat-mobile.png'});await send('/prd Certificate Alert Filtering');await page.getByRole('button',{name:'Approve non-conflicting items'}).click();await page.getByRole('button',{name:'Use September scope'}).click();await page.getByRole('button',{name:'Close context panel',exact:true}).last().click();await generate().click();await page.locator('.draft-document').waitFor();await page.screenshot({path:'test-results/chat-mobile-draft.png'});
 assert.deepEqual(errors,[]);console.log('PASS: chat requests, context review, edits, exclusions, receipts, updated decisions, context reuse in new chats, project isolation, own file input, honest local limitations, WebMCP adapter, and mobile flow.');await browser.close();
})().catch(e=>{console.error(e);process.exitCode=1;});
