const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{window.registeredTools=[];Object.defineProperty(document,'modelContext',{value:{registerTool:t=>window.registeredTools.push(t)}});});
 await page.goto('http://127.0.0.1:4173');
 await page.getByRole('heading',{name:'Your next PRD starts here.'}).waitFor();
 fs.mkdirSync('test-results',{recursive:true});
 await page.screenshot({path:'test-results/desktop-start.png',fullPage:true});
 await page.getByRole('button',{name:'Review team context'}).click();
 await page.getByRole('button',{name:'Approve non-conflicting items'}).click();
 assert.equal(await page.getByRole('button',{name:'Create draft with this context'}).isDisabled(),true);
 await page.getByRole('button',{name:'Use September scope'}).click();
 await page.locator('[data-memory="m4"]').getByRole('button',{name:'Reject',exact:true}).click();
 await page.locator('[data-memory="m5"]').getByRole('checkbox').uncheck();
 await page.locator('[data-memory="m1"]').getByRole('button',{name:'Edit',exact:true}).click();
 await page.locator('#edit-m1').fill('Enterprise security teams with 50+ domains');
 await page.getByRole('button',{name:'Save edit'}).click();
 await page.locator('[data-memory="m1"]').getByRole('button',{name:'Approve',exact:true}).click();
 await page.screenshot({path:'test-results/desktop-review.png',fullPage:true});
 await page.getByRole('button',{name:'Create draft with this context'}).click();
 await page.getByRole('heading',{name:'See what your context changes.'}).waitFor();
 const draft=page.locator('.compare .panel').nth(1);
 assert.ok((await draft.textContent()).includes('50+ domains'));
 assert.ok(!(await draft.textContent()).includes('Reduction in unnecessary alerts'));
 assert.ok(!(await draft.textContent()).includes('Preserve existing alert'));
 await page.screenshot({path:'test-results/desktop-compare.png',fullPage:true});
 await page.getByRole('button',{name:'Inspect Context Receipt'}).click();
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download receipt'}).click();
 const download=await downloadPromise;const r=JSON.parse(fs.readFileSync(await download.path(),'utf8'));
 assert.equal(r.contextSupplied.length,4);assert.equal(r.excluded.length,2);assert.equal(r.contextSupplied[0].edited,true);
 await page.getByRole('button',{name:'Test a project update'}).click();
 await page.getByRole('button',{name:'Propose context changes'}).click();
 await page.locator('.memory-card').first().getByRole('button',{name:'Approve',exact:true}).click();
 await page.locator('.memory-card').nth(1).getByRole('button',{name:'Reject',exact:true}).click();
 await page.getByRole('button',{name:'Apply approved updates'}).click();
 await page.getByRole('button',{name:'Generate the next draft'}).click();
 assert.ok((await page.locator('.compare .panel').nth(1).textContent()).includes('October 22, 2026'));
 assert.ok(!(await page.locator('.compare .panel').nth(1).textContent()).includes('dashboard and API users'));
 await page.getByRole('button',{name:'Your own context',exact:true}).click();
 await page.getByRole('button',{name:'Find proposed context'}).click();
 await page.getByRole('alert').waitFor();
 await page.locator('#task').fill('Draft a PRD for Mobile Launch');
 await page.locator('#note').fill('Scope: Mobile only\nMetric: Weekly retention\nConstraint: <img src=x onerror=alert(1)> must stay plain text');
 await page.getByRole('button',{name:'Find proposed context'}).click();
 assert.equal(await page.locator('img').count(),0);
 await page.getByRole('button',{name:'Approve non-conflicting items'}).click();
 await page.getByRole('button',{name:'Create draft with this context'}).click();
 assert.ok((await page.locator('.compare .panel').nth(1).textContent()).includes('Mobile only'));
 const toolResult=await page.evaluate(async()=>{const read=await window.registeredTools.find(t=>t.name==='read_context_review').execute({});const stage=window.registeredTools.find(t=>t.name==='stage_context_review');let failed=false;try{await stage.execute({unexpected:1});}catch{failed=true;}await stage.execute({});return {count:read.items.length,failed,heading:document.querySelector('h1').textContent};});
 assert.equal(toolResult.count,3);assert.equal(toolResult.failed,true);assert.equal(toolResult.heading,'A few decisions. One quick review.');
 await page.getByRole('button',{name:'Guided demo',exact:true}).click();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'test-results/mobile-start.png',fullPage:true});
 for(const width of [390,768,1440]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`overflow at ${width}`);}
 assert.deepEqual(errors,[]);console.log('PASS: guided review, conflict gate, edits, exclusions, receipt download, approved update, own notes, XSS escaping, WebMCP adapter, responsive widths; no browser errors.');
 await browser.close();
})().catch(e=>{console.error(e);process.exitCode=1;});
