import test from 'node:test';
import assert from 'node:assert/strict';
import worker from '../backend/worker.js';
const origin='https://jjjjeny.github.io';
function env(run){return {API_ENABLED:'true',ALLOWED_ORIGINS:origin,AI:{run},PER_VISITOR:{limit:async()=>({success:true})},PER_LOCATION:{limit:async()=>({success:true})}};}
function req(body,extra={}){return new Request('https://example.test/api/context',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json',...extra},body:JSON.stringify(body)});}
test('API fails closed when not configured',async()=>{const response=await worker.fetch(req({operation:'extract',text:'Scope: Mobile'}),{ALLOWED_ORIGINS:origin});assert.equal(response.status,503);});
test('CORS denies unrelated origins without AI calls',async()=>{let called=false;const r=await worker.fetch(req({},{Origin:'https://other.example'}),env(()=>{called=true;}));assert.equal(r.status,403);assert.equal(called,false);});
test('extract verifies excerpts before returning proposed context',async()=>{const r=await worker.fetch(req({operation:'extract',text:'Scope: Mobile only'}),env(async()=>({response:JSON.stringify({items:[{category:'Scope',text:'Mobile only',excerpt:'Scope: Mobile only'}]})})));assert.equal(r.status,200);assert.equal((await r.json()).items[0].text,'Mobile only');const bad=await worker.fetch(req({operation:'extract',text:'Scope: Mobile only'}),env(async()=>({response:JSON.stringify({items:[{category:'Scope',text:'Desktop',excerpt:'made up'}]})})));assert.equal(bad.status,502);});
test('draft uses identical model and instruction; reviewed call only sees supplied context',async()=>{const calls=[];const r=await worker.fetch(req({operation:'draft',task:'Write a PRD',text:'Scope: mobile. Secret: do not send this to reviewed draft.',context:[{id:'1',category:'Scope',text:'Mobile'}]}),env(async(model,params)=>{calls.push({model,params});return {response:'# PRD\nMobile'};}));assert.equal(r.status,200);assert.equal(calls.length,2);assert.equal(calls[0].model,calls[1].model);assert.equal(calls[0].params.messages[0].content,calls[1].params.messages[0].content);assert.ok(!calls[1].params.messages[1].content.includes('Secret'));});
test('rate limits and malformed context prevent generation',async()=>{const e=env(()=>{throw new Error('Should not run');});e.PER_VISITOR.limit=async()=>({success:false});assert.equal((await worker.fetch(req({operation:'extract',text:'Some note'}),e)).status,429);assert.equal((await worker.fetch(req({operation:'draft',text:'Some note',task:'PRD',context:[]}),e)).status,400);});
