const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome'});try{for(const viewport of [{width:1440,height:1050},{width:390,height:844}]){
 const page=await browser.newPage({viewport});const errors=[];page.on('pageerror',e=>errors.push(e.message));let sent,fail=false;
 await page.route('https://ai-memory-wallet-live.yajenn91.workers.dev/**',route=>{const data=route.request().postDataJSON();if(route.request().url().endsWith('/api/unlock'))return route.fulfill({json:{token:'fixture-only-token'}});sent=data;return route.fulfill({status:fail?502:200,json:fail?{error:'AI billing is not ready'}:{reply:sent.context.length?'TEST fixture with preference':'TEST fixture without preference'}});});
 await page.goto(process.env.PROTOTYPE_URL||'http://127.0.0.1:4173/');await page.getByRole('button',{name:'Unlock AI',exact:true}).click();await page.getByLabel('Demo password',{exact:true}).fill('fixture-password');await page.getByRole('dialog').getByRole('button',{name:'Unlock AI',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'+ Add',exact:true}).click();await page.getByLabel('Category',{exact:true}).selectOption('preference');await page.getByLabel('Title',{exact:true}).fill('My concise style');await page.getByLabel('Instructions or context').fill('Always answer in three concise bullets.');assert(await page.getByRole('checkbox',{name:'Use in my next reply'}).isChecked());await page.getByRole('dialog').getByRole('button',{name:'Save to wallet',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert.match(await page.locator('#selection').innerText(),/My concise style/);
 const ask=async()=>{await page.getByLabel('Message',{exact:true}).fill('Explain a roadmap');await page.getByRole('button',{name:'Send ↑',exact:true}).click();await page.getByRole('button',{name:'Send ↑',exact:true}).waitFor();await page.waitForFunction(()=>!document.querySelector('#send').disabled);};
 await ask();assert.equal(sent.context.length,1);assert.equal(sent.messages.length,1);
 await page.getByRole('button',{name:'Remove My concise style from chat',exact:true}).click();await ask();assert.equal(sent.context.length,0);assert.equal(sent.messages.length,1,'Old style must not leak through earlier replies');assert.equal(await page.locator('.bubble.assistant').count(),2);
 await page.getByRole('button',{name:'Backups',exact:true}).click();assert.equal(await page.getByLabel('Your backend URL').count(),0);assert.equal(await page.getByText('Save connection settings',{exact:true}).count(),0);await page.getByRole('button',{name:'Close',exact:true}).click();
 fail=true;await ask();assert.match(await page.locator('.bubble.system').last().innerText(),/billing/);assert.equal(await page.locator('.bubble.assistant').count(),2);
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`test-results/live-ui-${viewport.width}.png`,fullPage:true});assert.deepEqual(errors,[]);console.log(`PASS ${viewport.width}: unlock, auto-active preference, fresh context on removal, simple backups, honest error (mocked)`);await page.close();
}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
